development:
  adapter: postgresql
  encoding: unicode
  database: yandex_webmaster_api_development
  pool: 5
  username: postgres
  password: 123
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: yandex_webmaster_api_test
  pool: 5
  username: postgres
  password: 123
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: yandex_webmaster_api
  pool: 5
  username: 123
  password: 123
  host: 123

staging:
  host: postgresql2.locum.ru
  adapter: postgresql
  encoding: unicode
  database: yandex_webmaster_api
  pool: 5
  username: 123
  password: 123
